version: "3.9"
services:
  dev:
    build:
      context: .
      target: dev
    volumes:
      - "./:/app"
    ports:
      - "8000:8000"
  tests:
    build:
      context: .
      target: tests
    volumes:
      - "./:/app"
