[tool.poetry]
name = "chowda"
version = "0.0.1"
description = "A CLAMS processing application"
authors = ["WGBH-MLA"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8.1"
fastapi = "^0.92.0"
starlette-admin = "^0.5.2"
sqlmodel = "^0.0.8"
pydantic = {extras = ["email"], version = "^1.10.5"}
pydantic-factories = "^1.17.2"

[tool.poetry.group.dev.dependencies]
uvicorn = "^0.20.0"
black = "^23.1.0"
flake8 = "^6.0.0"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
pytest = "^7.2.1"
pytest-cov = "^4.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
