[tool.pdm.build]
includes = []

[build-system]
requires = ['pdm-backend']
build-backend = 'pdm.backend'

[project]
name = 'chowda'
dynamic = ['version']
description = 'A CLAMS processing application'
authors = [{ name = 'WGBH-MLA', email = 'ryan_harbert@wgbh.org' }]
dependencies = [
    "fastapi~=0.100",
    "starlette-admin~=0.10",
    "sqlmodel~=0.0",
    "pydantic[email]~=1.10",
    "sonyci~=0.1",
    "psycopg2~=2.9",
    "metaflow~=2.9",
    "alembic~=1.11",
    "python-dotenv~=1.0",
    "psycopg2~=2.9",
]
requires-python = '>=3.8.1,<4.0'
readme = 'README.md'
license = { text = 'MIT' }

[project.urls]
homepage = 'https://github.com/WGBH-MLA/chowda'
documentation = 'https://WGBH-MLA.github.io/chowda/'
repository = 'https://github.com/WGBH-MLA/chowda'

[project.optional-dependencies]
production = [
    "uvicorn[standard]~=0.22",
    "gunicorn~=20.1",
]
test = [
    "factory-boy~=3.2",
    "pytest~=7.4",
    "pytest-cov~=4.1",
    "pytest-sugar~=0.9",
    "pytest-xdist~=3.3",
    "httpx~=0.24",
    "nbmake~=1.4",
    "vcrpy~=5.0",
    "pytest-vcr~=1.0",
    "urllib3~=1.26",
]
locust = [
    "locust~=2.15",
    "pydantic-factories~=1.17",
]

[tool.pdm.dev-dependencies]
dev = [
    "uvicorn~=0.22",
    "black~=23.7",
    "ruff~=0.0",
    "pre-commit~=3.3",
]
docs = [
    "mkdocs~=1.4",
    "mkdocs-material~=9.1",
    "mkdocs-git-revision-date-localized-plugin~=1.2",
    "mike~=1.1",
    "mkdocstrings[python]~=0.22",
    "mkdocs-jupyter~=0.24",
]
ci = [
    "setuptools~=68.0",
]

[tool.pdm]
version = { source = 'file', path = 'chowda/_version.py' }

[tool.black]
extend-exclude = 'migrations'

[tool.coverage.run]
omit = ['tests/*']

[tool.pytest.ini_options]
testpaths = ['tests', 'docs']

[tool.ruff.flake8-quotes]
inline-quotes = 'single'

[tool.ruff]
extend-exclude = ['migrations']
select = [
    'B', # flake8-bugbear
    'C4', # flake8-comprehensions
    'C90', # mccabe
    'E', # pycodestyle errors
    'ERA', # eradicate
    'F', # pyflakes
    # 'I', # isort
    'INT', # flake8-gettext
    'N', # pep8-naming
    'PIE', # flake8-pie,
    'PLC', # pylint - convention
    'PLE', # pylint - error
    'PLW', # pylint - warning
    'Q', # flake8-quotes
    'RET', # flake8-return,
    'RUF', # Ruff-specific rules
    'SIM', # flake8-simplify
    'UP', # pyupgrade
    'W', # pycodestyle warnings

]
