[tool.pdm.build]
includes = []
[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[project]
name = "chowda"
dynamic = ["version"]
description = "A CLAMS processing application"
authors = [
    {name = "WGBH-MLA", email = "ryan_harbert@wgbh.org"},
]
dependencies = ["fastapi<1.0.0,>=0.92.0", "starlette-admin<1.0.0,>=0.5.2", "sqlmodel<1.0.0,>=0.0.8", "pydantic[email]<2.0.0,>=1.10.5"]
requires-python = ">=3.8.1,<4.0"
readme = "README.md"
license = {text = "MIT"}

[project.urls]
homepage = "https://github.com/WGBH-MLA/chowda"
documentation = "https://WGBH-MLA.github.io/chowda/"
repository = "https://github.com/WGBH-MLA/chowda"

[project.optional-dependencies]
production = [
    "psycopg2 >=2.9.5, < 3.0",
    "uvicorn[standard] >= 0.21.0",
    "gunicorn >= 20.1.0"
]
test = [
    "pydantic-factories >= 1.17.2",
    "pytest >= 7.2.1",
    "pytest-cov >= 4.0.0",
    "pytest-sugar >= 0.9.6",
    "pytest-xdist >= 3.2.1",
    "httpx >= 0.23.3"
]
locust = [
    "locust >= 2.15.1",
    "pydantic-factories >= 1.17.2",
]



[tool.pdm.dev-dependencies]
dev = [
    "uvicorn >= 0.21.0, < 1.0",
    "black >= 23.1.0, < 24.0.0",
    "flake8 >= 6.0.0, < 7.0.0"
]
docs = [
    "mkdocs >= 1.4.2",
    "mkdocs-material >= 9.1.3",
    "mkdocs-git-revision-date-localized-plugin >= 1.2.0",
    "mike @ git+https://github.com/jimporter/mike.git@063c93e9cce7c82939c7d47e6d33f99b24bba372",
    "mkdocstrings[python] >= 0.8.3",
]

[tool.pdm]
version = { source = "file", path = "chowda/_version.py" }

[tool.pytest.ini_options]
testpaths = ["tests"]
