[build-system]
requires = ['pdm-backend']
build-backend = 'pdm.backend'

[project]
name = 'chowda'
dynamic = ['version']
description = 'A CLAMS processing application'
authors = [{ name = 'WGBH-MLA', email = 'ryan_harbert@wgbh.org' }]
dependencies = [
    "fastapi~=0.103",
    "starlette-admin @ git+https://github.com/WGBH-MLA/starlette-admin.git@detail-actions",
    "sqlmodel~=0.0",
    "pydantic[email]~=1.10",
    "sonyci~=0.1",
    "psycopg2~=2.9",
    "metaflow~=2.9",
    "alembic~=1.12",
    "python-dotenv~=1.0",
    "authlib~=1.2",
    "itsdangerous~=2.1",
    "httpx~=0.25",
    "rich~=13.5",
]
requires-python = '>=3.8.1,<4.0'
readme = 'README.md'
license = { text = 'MIT' }

[project.urls]
homepage = 'https://github.com/WGBH-MLA/chowda'
documentation = 'https://WGBH-MLA.github.io/chowda/'
repository = 'https://github.com/WGBH-MLA/chowda'

[project.optional-dependencies]
production = [
    "uvicorn[standard]~=0.23",
    "gunicorn~=21.2",
]
test = [
    "factory-boy~=3.3",
    "pytest~=7.4",
    "pytest-cov~=4.1",
    "pytest-sugar~=0.9",
    "pytest-xdist~=3.3",
    "httpx~=0.25",
    "nbmake~=1.4",
    "vcrpy~=5.1",
    "pytest-vcr~=1.0",
    "urllib3~=1.26",
    "pytest-mock~=3.11",
    "pytest-asyncio~=0.21",
    "trio~=0.22",
]
locust = [
    "locust~=2.16",
    "pydantic-factories~=1.17",
]
development = [
    "kubernetes~=28.1",
]

[tool.black]
extend-exclude = 'migrations'

[tool.coverage.run]
omit = ['tests/*']

[tool.pytest.ini_options]
testpaths = ['tests', 'docs']

[tool.ruff]
extend-exclude = ['migrations']
ignore = ['Q000']
select = [
    'B', # flake8-bugbear
    'C4', # flake8-comprehensions
    'C90', # mccabe
    'E', # pycodestyle errors
    'ERA', # eradicate
    'F', # pyflakes
    # 'I', # isort
    'INT', # flake8-gettext
    'N', # pep8-naming
    'PIE', # flake8-pie,
    'PLC', # pylint - convention
    'PLE', # pylint - error
    'PLW', # pylint - warning
    'Q', # flake8-quotes
    'RET', # flake8-return,
    'RUF', # Ruff-specific rules
    'SIM', # flake8-simplify
    'UP', # pyupgrade
    'W', # pycodestyle warnings

]

[tool.pdm]
version = { source = 'file', path = 'chowda/_version.py' }

[tool.pdm.build]
includes = []

[tool.pdm.dev-dependencies]
dev = [
    "uvicorn~=0.23",
    "black~=23.9",
    "ruff~=0.0",
    "pre-commit~=3.4",
]
docs = [
    "mkdocs~=1.5",
    "mkdocs-material~=9.3",
    "mkdocs-git-revision-date-localized-plugin~=1.2",
    "mike~=1.1",
    "mkdocstrings[python]~=0.23",
    "mkdocs-jupyter~=0.24",
]
ci = [
    "setuptools~=68.2",
]
