[tool.poetry]
name = "chowda"
version = "0.0.1"
description = "A CLAMS processing application"
authors = ["WGBH-MLA"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
fastapi = "^0.88.0"
starlette-admin = "^0.5.2"
sqlmodel = "^0.0.8"
pydantic = {extras = ["email"], version = "^1.10.5"}

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
uvicorn = "^0.20.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
