[tool.poetry]
name = "chowda"
version = "0.0.1"
description = "A CLAMS processing application"
authors = ["WGBH-MLA"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8.1"
fastapi = "^0.92.0"
starlette-admin = "^0.5.2"
sqlmodel = "^0.0.8"
pydantic = {extras = ["email"], version = "^1.10.5"}

[tool.poetry.group.dev.dependencies]
uvicorn = "^0.20.0"
black = "^23.1.0"
flake8 = "^6.0.0"
pydantic-factories = "^1.17.2"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
pytest = "^7.2.1"
pytest-cov = "^4.0.0"
pytest-sugar = "^0.9.6"
pytest-xdist = "^3.2.1"
httpx = "^0.23.3"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
mkdocs = "^1.4.2"
mkdocstrings = {extras = ["python"], version = "^0.20.0"}
mkdocs-material = "^9.1.3"
mkdocs-git-revision-date-localized-plugin = "^1.2.0"
mike = "^1.1.2"
mkdocstrings-python = "^0.8.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
