"""Allow None AssetType

Revision ID: 1d3442a08535
Revises: 3b40432bd201
Create Date: 2026-06-25 16:54:27.687522

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision = '1d3442a08535'
down_revision = '3b40432bd201'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='assettype',
        new_values=['Audio', 'Video', 'Image', 'Document', 'TimedText', 'Other', 'NoneType'],
        affected_columns=[TableReference(table_schema='public', table_name='sonyci_assets', column_name='type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='assettype',
        new_values=['Audio', 'Video', 'Image', 'Document', 'TimedText', 'Other'],
        affected_columns=[TableReference(table_schema='public', table_name='sonyci_assets', column_name='type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
