"""MetaflowRun.current_step

Revision ID: 42a163f0faec
Revises: 775fe282e786
Create Date: 2023-09-13 14:08:11.667021

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '42a163f0faec'
down_revision = '775fe282e786'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metaflow_runs', sa.Column('current_step', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('metaflow_runs', sa.Column('current_task', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metaflow_runs', 'current_task')
    op.drop_column('metaflow_runs', 'current_step')
    # ### end Alembic commands ###
