"""Adds undocumented UploadTransferType: ClipFromSource

Revision ID: 43427c47080b
Revises: 808cace84505
Create Date: 2026-08-04 12:42:23.154101

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision = '43427c47080b'
down_revision = '808cace84505'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='sonyciuploadtransfertype',
        new_values=['SinglepartHttp', 'MultipartHttp', 'Aspera', 'Copy', 'FTP', 'WorkspaceSend', 'ClipFromSource'],
        affected_columns=[TableReference(table_schema='public', table_name='sonyci_assets', column_name='uploadTransferType'), TableReference(table_schema='public', table_name='sonyci_trashbin', column_name='uploadTransferType')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='sonyciuploadtransfertype',
        new_values=['SinglepartHttp', 'MultipartHttp', 'Aspera', 'Copy', 'FTP', 'WorkspaceSend'],
        affected_columns=[TableReference(table_schema='public', table_name='sonyci_assets', column_name='uploadTransferType'), TableReference(table_schema='public', table_name='sonyci_trashbin', column_name='uploadTransferType')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
