"""SonyCiEvent

Revision ID: 46cd52ab7e22
Revises: 43427c47080b
Create Date: 2026-09-09 23:00:22.780425

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '46cd52ab7e22'
down_revision = '43427c47080b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('MoveAsset', 'CopyAsset', 'TrashAsset', 'DeleteAsset', 'DeleteElement', 'JobStatusChange', 'AssetProcessingFinished', 'ElementProcessingFinished', 'AssetArchiveStatusChange', 'AssetRestoreStatusChange', 'LockElement', 'UnlockElement', 'CopyAssetsToWorkspace', 'CopyAssetsToCatalog', 'AssetMetadataChange', 'ElementMetadataChange', name='sonycieventtype').create(op.get_bind())
    op.create_table('sonyci_events',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', postgresql.ENUM('MoveAsset', 'CopyAsset', 'TrashAsset', 'DeleteAsset', 'DeleteElement', 'JobStatusChange', 'AssetProcessingFinished', 'ElementProcessingFinished', 'AssetArchiveStatusChange', 'AssetRestoreStatusChange', 'LockElement', 'UnlockElement', 'CopyAssetsToWorkspace', 'CopyAssetsToCatalog', 'AssetMetadataChange', 'ElementMetadataChange', name='sonycieventtype', create_type=False), nullable=True),
    sa.Column('createdOn', sa.DateTime(), nullable=True),
    sa.Column('createdBy', sa.JSON(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sonyci_events_createdOn'), 'sonyci_events', ['createdOn'], unique=False)
    op.create_index(op.f('ix_sonyci_events_created_at'), 'sonyci_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_sonyci_events_id'), 'sonyci_events', ['id'], unique=False)
    op.create_index(op.f('ix_sonyci_events_type'), 'sonyci_events', ['type'], unique=False)
    op.create_table('sonyci_event_asset_links',
    sa.Column('event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['sonyci_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['sonyci_events.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'asset_id')
    )
    op.create_index(op.f('ix_sonyci_event_asset_links_asset_id'), 'sonyci_event_asset_links', ['asset_id'], unique=False)
    op.create_index(op.f('ix_sonyci_event_asset_links_event_id'), 'sonyci_event_asset_links', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sonyci_event_asset_links_event_id'), table_name='sonyci_event_asset_links')
    op.drop_index(op.f('ix_sonyci_event_asset_links_asset_id'), table_name='sonyci_event_asset_links')
    op.drop_table('sonyci_event_asset_links')
    op.drop_index(op.f('ix_sonyci_events_type'), table_name='sonyci_events')
    op.drop_index(op.f('ix_sonyci_events_id'), table_name='sonyci_events')
    op.drop_index(op.f('ix_sonyci_events_created_at'), table_name='sonyci_events')
    op.drop_index(op.f('ix_sonyci_events_createdOn'), table_name='sonyci_events')
    op.drop_table('sonyci_events')
    sa.Enum('MoveAsset', 'CopyAsset', 'TrashAsset', 'DeleteAsset', 'DeleteElement', 'JobStatusChange', 'AssetProcessingFinished', 'ElementProcessingFinished', 'AssetArchiveStatusChange', 'AssetRestoreStatusChange', 'LockElement', 'UnlockElement', 'CopyAssetsToWorkspace', 'CopyAssetsToCatalog', 'AssetMetadataChange', 'ElementMetadataChange', name='sonycieventtype').drop(op.get_bind())
    # ### end Alembic commands ###
