"""chowda maintenance

Revision ID: 4899b7f6959a
Revises: 6a71376e4001
Create Date: 2024-10-09 08:18:06.252355

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '4899b7f6959a'
down_revision = '6a71376e4001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_clams_apps_endpoint'), 'clams_apps', ['endpoint'], unique=False)
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.drop_index(op.f('ix_clams_apps_endpoint'), table_name='clams_apps')
    # ### end Alembic commands ###
