"""MMIFs

Revision ID: 4b8df341aeff
Revises: 42a163f0faec
Create Date: 2023-10-13 10:02:23.104677

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4b8df341aeff'
down_revision = '42a163f0faec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mmifs',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mmif_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_file_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('metaflow_run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('batch_output_id', sa.Integer(), nullable=True),
    sa.Column('batch_input_id', sa.Integer(), nullable=True),
    sa.Column('mmif_location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['batch_input_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['batch_output_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['media_file_id'], ['media_files.guid'], ),
    sa.ForeignKeyConstraint(['metaflow_run_id'], ['metaflow_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('mediafilesonyciassetlink')
    op.alter_column('metaflow_runs', 'finished_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.add_column('sonyci_assets', sa.Column('media_file_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'sonyci_assets', 'media_files', ['media_file_id'], ['guid'])

    op.execute("ALTER TYPE mediatype RENAME VALUE 'video' TO 'Video';")
    op.execute("ALTER TYPE mediatype RENAME VALUE 'audio' TO 'Audio';")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sonyci_assets', type_='foreignkey')
    op.drop_column('sonyci_assets', 'media_file_id')
    op.alter_column('metaflow_runs', 'finished_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.create_table('mediafilesonyciassetlink',
    sa.Column('media_file_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sonyci_asset_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['media_file_id'], ['media_files.guid'], name='mediafilesonyciassetlink_media_file_id_fkey'),
    sa.ForeignKeyConstraint(['sonyci_asset_id'], ['sonyci_assets.id'], name='mediafilesonyciassetlink_sonyci_asset_id_fkey'),
    sa.PrimaryKeyConstraint('media_file_id', 'sonyci_asset_id', name='mediafilesonyciassetlink_pkey')
    )
    op.drop_table('mmifs')

    op.execute("ALTER TYPE mediatype RENAME VALUE 'Video' TO 'video';")
    op.execute("ALTER TYPE mediatype RENAME VALUE 'Audio' TO 'audio';")
    # ### end Alembic commands ###
