"""Initial transcript model

Revision ID: 4f310ebc620d
Revises: 4899b7f6959a
Create Date: 2024-10-15 13:49:51.830372

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '4f310ebc620d'
down_revision = '4899b7f6959a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('media_file_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['media_file_id'], ['media_files.guid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcripts_id'), 'transcripts', ['id'], unique=False)
    op.create_index(op.f('ix_transcripts_media_file_id'), 'transcripts', ['media_file_id'], unique=False)
    op.create_table('mediafiletranscriptlink',
    sa.Column('media_file_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transcript_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['media_file_id'], ['media_files.guid'], ),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ),
    sa.PrimaryKeyConstraint('media_file_id', 'transcript_id')
    )
    op.create_index(op.f('ix_mediafiletranscriptlink_media_file_id'), 'mediafiletranscriptlink', ['media_file_id'], unique=False)
    op.create_index(op.f('ix_mediafiletranscriptlink_transcript_id'), 'mediafiletranscriptlink', ['transcript_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mediafiletranscriptlink_transcript_id'), table_name='mediafiletranscriptlink')
    op.drop_index(op.f('ix_mediafiletranscriptlink_media_file_id'), table_name='mediafiletranscriptlink')
    op.drop_table('mediafiletranscriptlink')
    op.drop_index(op.f('ix_transcripts_media_file_id'), table_name='transcripts')
    op.drop_index(op.f('ix_transcripts_id'), table_name='transcripts')
    op.drop_table('transcripts')
    # ### end Alembic commands ###
