"""Adds metaflow_runs table from MetaflowRun model

Revision ID: 63cbfe6a272a
Revises: 9c426736beb0
Create Date: 2023-08-26 17:39:25.889680

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '63cbfe6a272a'
down_revision = '9c426736beb0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metaflow_runs',
    sa.Column('response_json', sa.JSON(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('media_file_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['media_file_id'], ['media_files.guid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('clams_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clams_events',
    sa.Column('response_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('batch_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('clams_app_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('media_file_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], name='clams_events_batch_id_fkey'),
    sa.ForeignKeyConstraint(['clams_app_id'], ['clams_apps.id'], name='clams_events_clams_app_id_fkey'),
    sa.ForeignKeyConstraint(['media_file_id'], ['media_files.guid'], name='clams_events_media_file_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='clams_events_pkey')
    )
    op.drop_table('metaflow_runs')
    # ### end Alembic commands ###
