"""Adds other SonyCi AssetTypes

Revision ID: 74800f24a8cf
Revises: 4899b7f6959a
Create Date: 2026-05-21 12:03:17.927982

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '74800f24a8cf'
down_revision = '4899b7f6959a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE mediatype RENAME TO assettype")
    op.execute("ALTER TYPE assettype ADD VALUE 'Image'")
    op.execute("ALTER TYPE assettype ADD VALUE 'Document'")
    op.execute("ALTER TYPE assettype ADD VALUE 'TimedText'")
    op.execute("ALTER TYPE assettype ADD VALUE 'Other'")


# ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE assettype RENAME TO mediatype")
    # Note: Postgres does not support removing enum values, so we can't remove the added values.
    # ### end Alembic commands ###
