"""Adds more SonyCiAsset fields and types

Revision ID: 758afdcc3311
Revises: 74800f24a8cf
Create Date: 2026-06-24 15:07:56.177326

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '758afdcc3311'
down_revision = '74800f24a8cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('SinglepartHttp', 'MultipartHttp', 'Aspera', 'Copy', 'FTP', 'WorkspaceSend', name='sonyciuploadtransfertype').create(op.get_bind())
    sa.Enum('NotRestored', 'RestoreInProgress', 'RestoreFailed', 'Restored', name='sonycirestorestatus').create(op.get_bind())
    sa.Enum('NotArchived', 'ArchiveInProgress', 'Archived', 'RestoreInProgress', 'Restored', name='sonyciarchivestatus').create(op.get_bind())
    sa.Enum('Created', 'Waiting', 'Processing', 'Complete', 'Failed', 'Limited', 'VirusDetected', 'ExecutableDetected', 'Deleted', name='sonyciassetstatus').create(op.get_bind())
    op.add_column('sonyci_assets', sa.Column('createdOn', sa.DateTime(), nullable=True))
    op.add_column('sonyci_assets', sa.Column('modifiedOn', sa.DateTime(), nullable=True))
    op.add_column('sonyci_assets', sa.Column('folder', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('sonyci_assets', sa.Column('md5Checksum', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('sonyci_assets', sa.Column('status', postgresql.ENUM('Created', 'Waiting', 'Processing', 'Complete', 'Failed', 'Limited', 'VirusDetected', 'ExecutableDetected', 'Deleted', name='sonyciassetstatus', create_type=False), nullable=True))
    op.add_column('sonyci_assets', sa.Column('archive_status', postgresql.ENUM('NotArchived', 'ArchiveInProgress', 'Archived', 'RestoreInProgress', 'Restored', name='sonyciarchivestatus', create_type=False), nullable=True))
    op.add_column('sonyci_assets', sa.Column('restore_status', postgresql.ENUM('NotRestored', 'RestoreInProgress', 'RestoreFailed', 'Restored', name='sonycirestorestatus', create_type=False), nullable=True))
    op.add_column('sonyci_assets', sa.Column('isDeleted', sa.Boolean(), nullable=True))
    op.add_column('sonyci_assets', sa.Column('isTrashed', sa.Boolean(), nullable=True))
    op.add_column('sonyci_assets', sa.Column('runtime', sa.Float(), nullable=True))
    op.add_column('sonyci_assets', sa.Column('lastActivityOn', sa.DateTime(), nullable=True))
    op.add_column('sonyci_assets', sa.Column('uploadCompleteDate', sa.DateTime(), nullable=True))
    op.add_column('sonyci_assets', sa.Column('uploadTransferType', postgresql.ENUM('SinglepartHttp', 'MultipartHttp', 'Aspera', 'Copy', 'FTP', 'WorkspaceSend', name='sonyciuploadtransfertype', create_type=False), nullable=True))
    op.add_column('sonyci_assets', sa.Column('hasPlayableProxies', sa.Boolean(), nullable=True))
    op.add_column('sonyci_assets', sa.Column('generatingPlayableProxies', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_sonyci_assets_createdOn'), 'sonyci_assets', ['createdOn'], unique=False)
    op.create_index(op.f('ix_sonyci_assets_folder'), 'sonyci_assets', ['folder'], unique=False)
    op.create_index(op.f('ix_sonyci_assets_generatingPlayableProxies'), 'sonyci_assets', ['generatingPlayableProxies'], unique=False)
    op.create_index(op.f('ix_sonyci_assets_hasPlayableProxies'), 'sonyci_assets', ['hasPlayableProxies'], unique=False)
    op.create_index(op.f('ix_sonyci_assets_isDeleted'), 'sonyci_assets', ['isDeleted'], unique=False)
    op.create_index(op.f('ix_sonyci_assets_isTrashed'), 'sonyci_assets', ['isTrashed'], unique=False)
    op.create_index(op.f('ix_sonyci_assets_lastActivityOn'), 'sonyci_assets', ['lastActivityOn'], unique=False)
    op.create_index(op.f('ix_sonyci_assets_md5Checksum'), 'sonyci_assets', ['md5Checksum'], unique=False)
    op.create_index(op.f('ix_sonyci_assets_modifiedOn'), 'sonyci_assets', ['modifiedOn'], unique=False)
    op.create_index(op.f('ix_sonyci_assets_runtime'), 'sonyci_assets', ['runtime'], unique=False)
    op.create_index(op.f('ix_sonyci_assets_uploadCompleteDate'), 'sonyci_assets', ['uploadCompleteDate'], unique=False)
    op.sync_enum_values(
        enum_schema='public',
        enum_name='assettype',
        new_values=['Audio', 'Video', 'Image', 'Document', 'TimedText', 'Other'],
        affected_columns=[TableReference(table_schema='public', table_name='sonyci_assets', column_name='type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='assettype',
        new_values=['Video', 'Audio', 'Image', 'Document', 'TimedText', 'Other'],
        affected_columns=[TableReference(table_schema='public', table_name='sonyci_assets', column_name='type')],
        enum_values_to_rename=[],
    )
    op.drop_index(op.f('ix_sonyci_assets_uploadCompleteDate'), table_name='sonyci_assets')
    op.drop_index(op.f('ix_sonyci_assets_runtime'), table_name='sonyci_assets')
    op.drop_index(op.f('ix_sonyci_assets_modifiedOn'), table_name='sonyci_assets')
    op.drop_index(op.f('ix_sonyci_assets_md5Checksum'), table_name='sonyci_assets')
    op.drop_index(op.f('ix_sonyci_assets_lastActivityOn'), table_name='sonyci_assets')
    op.drop_index(op.f('ix_sonyci_assets_isTrashed'), table_name='sonyci_assets')
    op.drop_index(op.f('ix_sonyci_assets_isDeleted'), table_name='sonyci_assets')
    op.drop_index(op.f('ix_sonyci_assets_hasPlayableProxies'), table_name='sonyci_assets')
    op.drop_index(op.f('ix_sonyci_assets_generatingPlayableProxies'), table_name='sonyci_assets')
    op.drop_index(op.f('ix_sonyci_assets_folder'), table_name='sonyci_assets')
    op.drop_index(op.f('ix_sonyci_assets_createdOn'), table_name='sonyci_assets')
    op.drop_column('sonyci_assets', 'generatingPlayableProxies')
    op.drop_column('sonyci_assets', 'hasPlayableProxies')
    op.drop_column('sonyci_assets', 'uploadTransferType')
    op.drop_column('sonyci_assets', 'uploadCompleteDate')
    op.drop_column('sonyci_assets', 'lastActivityOn')
    op.drop_column('sonyci_assets', 'runtime')
    op.drop_column('sonyci_assets', 'isTrashed')
    op.drop_column('sonyci_assets', 'isDeleted')
    op.drop_column('sonyci_assets', 'restore_status')
    op.drop_column('sonyci_assets', 'archive_status')
    op.drop_column('sonyci_assets', 'status')
    op.drop_column('sonyci_assets', 'md5Checksum')
    op.drop_column('sonyci_assets', 'folder')
    op.drop_column('sonyci_assets', 'modifiedOn')
    op.drop_column('sonyci_assets', 'createdOn')
    sa.Enum('Created', 'Waiting', 'Processing', 'Complete', 'Failed', 'Limited', 'VirusDetected', 'ExecutableDetected', 'Deleted', name='sonyciassetstatus').drop(op.get_bind())
    sa.Enum('NotArchived', 'ArchiveInProgress', 'Archived', 'RestoreInProgress', 'Restored', name='sonyciarchivestatus').drop(op.get_bind())
    sa.Enum('NotRestored', 'RestoreInProgress', 'RestoreFailed', 'Restored', name='sonycirestorestatus').drop(op.get_bind())
    sa.Enum('SinglepartHttp', 'MultipartHttp', 'Aspera', 'Copy', 'FTP', 'WorkspaceSend', name='sonyciuploadtransfertype').drop(op.get_bind())
    # ### end Alembic commands ###
