"""MetaflowRun.created_at with timezone

Revision ID: 775fe282e786
Revises: fd7b62eab884
Create Date: 2023-09-08 11:19:21.339487

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '775fe282e786'
down_revision = 'fd7b62eab884'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metaflow_runs', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('metaflow_runs', 'duration')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metaflow_runs', sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('metaflow_runs', 'created_at')
    # ### end Alembic commands ###
