"""add sonyci_trashbin and sonyci asset fields

Revision ID: d0dbc16a01b4
Revises: 1d3442a08535
Create Date: 2026-07-30 10:40:11.249726

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd0dbc16a01b4'
down_revision = '1d3442a08535'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sonyci_trashbin',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size', sa.BIGINT(), nullable=False),
    sa.Column('createdOn', sa.DateTime(), nullable=True),
    sa.Column('createdBy', sa.JSON(), nullable=True),
    sa.Column('modifiedOn', sa.DateTime(), nullable=True),
    sa.Column('lastActivityOn', sa.DateTime(), nullable=True),
    sa.Column('acquisitionSource', sa.JSON(), nullable=True),
    sa.Column('type', postgresql.ENUM('Audio', 'Video', 'Image', 'Document', 'TimedText', 'Other', 'NoneType', name='assettype', create_type=False), nullable=True),
    sa.Column('format', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('folder', sa.JSON(), nullable=True),
    sa.Column('md5Checksum', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', postgresql.ENUM('Created', 'Complete', 'Deleted', 'ExecutableDetected', 'Failed', 'Limited', 'Processing', 'Uploading', 'VirusDetected', 'Waiting', name='sonyciassetstatus', create_type=False), nullable=True),
    sa.Column('archiveStatus', postgresql.ENUM('NotArchived', 'ArchiveInProgress', 'Archived', 'RestoreInProgress', 'Restored', name='sonyciarchivestatus', create_type=False), nullable=True),
    sa.Column('restoreStatus', postgresql.ENUM('NotRestored', 'RestoreInProgress', 'RestoreFailed', 'Restored', name='sonycirestorestatus', create_type=False), nullable=True),
    sa.Column('isTrashed', sa.Boolean(), nullable=True),
    sa.Column('runtime', sa.Float(), nullable=True),
    sa.Column('totalFolderCount', sa.Integer(), nullable=True),
    sa.Column('asset_metadata', postgresql.ARRAY(sa.JSON()), nullable=True),
    sa.Column('uploadCompleteDate', sa.DateTime(), nullable=True),
    sa.Column('uploadTransferType', postgresql.ENUM('SinglepartHttp', 'MultipartHttp', 'Aspera', 'Copy', 'FTP', 'WorkspaceSend', name='sonyciuploadtransfertype', create_type=False), nullable=True),
    sa.Column('hasPlayableProxies', sa.Boolean(), nullable=True),
    sa.Column('generatingPlayableProxies', sa.Boolean(), nullable=True),
    sa.Column('thumbnails', postgresql.ARRAY(sa.JSON()), nullable=True),
    sa.Column('proxies', postgresql.ARRAY(sa.JSON()), nullable=True),
    sa.Column('filmstrips', postgresql.ARRAY(sa.JSON()), nullable=True),
    sa.Column('technicalMetadata', sa.JSON(), nullable=True),
    sa.Column('technicalMetadataUpdates', sa.JSON(), nullable=True),
    sa.Column('waveforms', postgresql.ARRAY(sa.JSON()), nullable=True),
    sa.Column('media_file_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('statusDescription', sa.JSON(), nullable=True),
    sa.Column('trashedOn', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['media_file_id'], ['media_files.guid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sonyci_trashbin_createdOn'), 'sonyci_trashbin', ['createdOn'], unique=False)
    op.create_index(op.f('ix_sonyci_trashbin_format'), 'sonyci_trashbin', ['format'], unique=False)
    op.create_index(op.f('ix_sonyci_trashbin_generatingPlayableProxies'), 'sonyci_trashbin', ['generatingPlayableProxies'], unique=False)
    op.create_index(op.f('ix_sonyci_trashbin_hasPlayableProxies'), 'sonyci_trashbin', ['hasPlayableProxies'], unique=False)
    op.create_index(op.f('ix_sonyci_trashbin_id'), 'sonyci_trashbin', ['id'], unique=False)
    op.create_index(op.f('ix_sonyci_trashbin_isTrashed'), 'sonyci_trashbin', ['isTrashed'], unique=False)
    op.create_index(op.f('ix_sonyci_trashbin_lastActivityOn'), 'sonyci_trashbin', ['lastActivityOn'], unique=False)
    op.create_index(op.f('ix_sonyci_trashbin_md5Checksum'), 'sonyci_trashbin', ['md5Checksum'], unique=False)
    op.create_index(op.f('ix_sonyci_trashbin_media_file_id'), 'sonyci_trashbin', ['media_file_id'], unique=False)
    op.create_index(op.f('ix_sonyci_trashbin_modifiedOn'), 'sonyci_trashbin', ['modifiedOn'], unique=False)
    op.create_index(op.f('ix_sonyci_trashbin_name'), 'sonyci_trashbin', ['name'], unique=False)
    op.create_index(op.f('ix_sonyci_trashbin_runtime'), 'sonyci_trashbin', ['runtime'], unique=False)
    op.create_index(op.f('ix_sonyci_trashbin_totalFolderCount'), 'sonyci_trashbin', ['totalFolderCount'], unique=False)
    op.create_index(op.f('ix_sonyci_trashbin_trashedOn'), 'sonyci_trashbin', ['trashedOn'], unique=False)
    op.create_index(op.f('ix_sonyci_trashbin_uploadCompleteDate'), 'sonyci_trashbin', ['uploadCompleteDate'], unique=False)
    op.add_column('sonyci_assets', sa.Column('createdBy', sa.JSON(), nullable=True))
    op.add_column('sonyci_assets', sa.Column('acquisitionSource', sa.JSON(), nullable=True))
    op.add_column('sonyci_assets', sa.Column('archiveStatus', postgresql.ENUM('NotArchived', 'ArchiveInProgress', 'Archived', 'RestoreInProgress', 'Restored', name='sonyciarchivestatus', create_type=False), nullable=True))
    op.add_column('sonyci_assets', sa.Column('restoreStatus', postgresql.ENUM('NotRestored', 'RestoreInProgress', 'RestoreFailed', 'Restored', name='sonycirestorestatus', create_type=False), nullable=True))
    op.add_column('sonyci_assets', sa.Column('totalFolderCount', sa.Integer(), nullable=True))
    op.add_column('sonyci_assets', sa.Column('asset_metadata', postgresql.ARRAY(sa.JSON()), nullable=True))
    op.alter_column('sonyci_assets', 'size',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_index(op.f('ix_sonyci_assets_isDeleted'), table_name='sonyci_assets')
    op.create_index(op.f('ix_sonyci_assets_totalFolderCount'), 'sonyci_assets', ['totalFolderCount'], unique=False)
    op.drop_column('sonyci_assets', 'archive_status')
    op.drop_column('sonyci_assets', 'isDeleted')
    op.drop_column('sonyci_assets', 'restore_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sonyci_assets', sa.Column('restore_status', postgresql.ENUM('NotRestored', 'RestoreInProgress', 'RestoreFailed', 'Restored', name='sonycirestorestatus', create_type=False), autoincrement=False, nullable=True))
    op.add_column('sonyci_assets', sa.Column('isDeleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('sonyci_assets', sa.Column('archive_status', postgresql.ENUM('NotArchived', 'ArchiveInProgress', 'Archived', 'RestoreInProgress', 'Restored', name='sonyciarchivestatus', create_type=False), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_sonyci_assets_totalFolderCount'), table_name='sonyci_assets')
    op.create_index(op.f('ix_sonyci_assets_isDeleted'), 'sonyci_assets', ['isDeleted'], unique=False)
    op.alter_column('sonyci_assets', 'size',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_column('sonyci_assets', 'asset_metadata')
    op.drop_column('sonyci_assets', 'totalFolderCount')
    op.drop_column('sonyci_assets', 'restoreStatus')
    op.drop_column('sonyci_assets', 'archiveStatus')
    op.drop_column('sonyci_assets', 'acquisitionSource')
    op.drop_column('sonyci_assets', 'createdBy')
    op.drop_index(op.f('ix_sonyci_trashbin_uploadCompleteDate'), table_name='sonyci_trashbin')
    op.drop_index(op.f('ix_sonyci_trashbin_trashedOn'), table_name='sonyci_trashbin')
    op.drop_index(op.f('ix_sonyci_trashbin_totalFolderCount'), table_name='sonyci_trashbin')
    op.drop_index(op.f('ix_sonyci_trashbin_runtime'), table_name='sonyci_trashbin')
    op.drop_index(op.f('ix_sonyci_trashbin_name'), table_name='sonyci_trashbin')
    op.drop_index(op.f('ix_sonyci_trashbin_modifiedOn'), table_name='sonyci_trashbin')
    op.drop_index(op.f('ix_sonyci_trashbin_media_file_id'), table_name='sonyci_trashbin')
    op.drop_index(op.f('ix_sonyci_trashbin_md5Checksum'), table_name='sonyci_trashbin')
    op.drop_index(op.f('ix_sonyci_trashbin_lastActivityOn'), table_name='sonyci_trashbin')
    op.drop_index(op.f('ix_sonyci_trashbin_isTrashed'), table_name='sonyci_trashbin')
    op.drop_index(op.f('ix_sonyci_trashbin_id'), table_name='sonyci_trashbin')
    op.drop_index(op.f('ix_sonyci_trashbin_hasPlayableProxies'), table_name='sonyci_trashbin')
    op.drop_index(op.f('ix_sonyci_trashbin_generatingPlayableProxies'), table_name='sonyci_trashbin')
    op.drop_index(op.f('ix_sonyci_trashbin_format'), table_name='sonyci_trashbin')
    op.drop_index(op.f('ix_sonyci_trashbin_createdOn'), table_name='sonyci_trashbin')
    op.drop_table('sonyci_trashbin')
    # ### end Alembic commands ###
