"""SonyCi Assets

Revision ID: d2d597934136
Revises: d10392cd5788
Create Date: 2023-07-07 10:15:54.989905

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd2d597934136'
down_revision = 'd10392cd5788'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sonyci_assets',
    sa.Column('type', sa.Enum('video', 'audio', name='mediatype'), nullable=True),
    sa.Column('thumbnails', postgresql.ARRAY(sa.JSON()), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('format', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sonyci_assets_format'), 'sonyci_assets', ['format'], unique=False)
    op.create_index(op.f('ix_sonyci_assets_id'), 'sonyci_assets', ['id'], unique=False)
    op.create_index(op.f('ix_sonyci_assets_name'), 'sonyci_assets', ['name'], unique=False)
    op.create_index(op.f('ix_sonyci_assets_size'), 'sonyci_assets', ['size'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sonyci_assets_size'), table_name='sonyci_assets')
    op.drop_index(op.f('ix_sonyci_assets_name'), table_name='sonyci_assets')
    op.drop_index(op.f('ix_sonyci_assets_id'), table_name='sonyci_assets')
    op.drop_index(op.f('ix_sonyci_assets_format'), table_name='sonyci_assets')
    op.drop_table('sonyci_assets')
    # ### end Alembic commands ###
