"""Upgrades to sqlmodel 0.0.46

Revision ID: e2fd6b722702
Revises: 46cd52ab7e22
Create Date: 2026-09-25 14:39:02.432604

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e2fd6b722702'
down_revision = '46cd52ab7e22'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sonyci_assets', 'createdOn',
               existing_type=postgresql.TIMESTAMP(),
               type_=sqlmodel.sql.sqltypes.UTCDateTime(),
               existing_nullable=True)
    op.alter_column('sonyci_assets', 'modifiedOn',
               existing_type=postgresql.TIMESTAMP(),
               type_=sqlmodel.sql.sqltypes.UTCDateTime(),
               existing_nullable=True)
    op.alter_column('sonyci_assets', 'lastActivityOn',
               existing_type=postgresql.TIMESTAMP(),
               type_=sqlmodel.sql.sqltypes.UTCDateTime(),
               existing_nullable=True)
    op.alter_column('sonyci_assets', 'uploadCompleteDate',
               existing_type=postgresql.TIMESTAMP(),
               type_=sqlmodel.sql.sqltypes.UTCDateTime(),
               existing_nullable=True)
    op.alter_column('sonyci_events', 'createdOn',
               existing_type=postgresql.TIMESTAMP(),
               type_=sqlmodel.sql.sqltypes.UTCDateTime(),
               existing_nullable=True)
    op.alter_column('sonyci_trashbin', 'createdOn',
               existing_type=postgresql.TIMESTAMP(),
               type_=sqlmodel.sql.sqltypes.UTCDateTime(),
               existing_nullable=True)
    op.alter_column('sonyci_trashbin', 'modifiedOn',
               existing_type=postgresql.TIMESTAMP(),
               type_=sqlmodel.sql.sqltypes.UTCDateTime(),
               existing_nullable=True)
    op.alter_column('sonyci_trashbin', 'lastActivityOn',
               existing_type=postgresql.TIMESTAMP(),
               type_=sqlmodel.sql.sqltypes.UTCDateTime(),
               existing_nullable=True)
    op.alter_column('sonyci_trashbin', 'uploadCompleteDate',
               existing_type=postgresql.TIMESTAMP(),
               type_=sqlmodel.sql.sqltypes.UTCDateTime(),
               existing_nullable=True)
    op.alter_column('sonyci_trashbin', 'trashedOn',
               existing_type=postgresql.TIMESTAMP(),
               type_=sqlmodel.sql.sqltypes.UTCDateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sonyci_trashbin', 'trashedOn',
               existing_type=sqlmodel.sql.sqltypes.UTCDateTime(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('sonyci_trashbin', 'uploadCompleteDate',
               existing_type=sqlmodel.sql.sqltypes.UTCDateTime(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('sonyci_trashbin', 'lastActivityOn',
               existing_type=sqlmodel.sql.sqltypes.UTCDateTime(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('sonyci_trashbin', 'modifiedOn',
               existing_type=sqlmodel.sql.sqltypes.UTCDateTime(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('sonyci_trashbin', 'createdOn',
               existing_type=sqlmodel.sql.sqltypes.UTCDateTime(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('sonyci_events', 'createdOn',
               existing_type=sqlmodel.sql.sqltypes.UTCDateTime(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('sonyci_assets', 'uploadCompleteDate',
               existing_type=sqlmodel.sql.sqltypes.UTCDateTime(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('sonyci_assets', 'lastActivityOn',
               existing_type=sqlmodel.sql.sqltypes.UTCDateTime(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('sonyci_assets', 'modifiedOn',
               existing_type=sqlmodel.sql.sqltypes.UTCDateTime(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('sonyci_assets', 'createdOn',
               existing_type=sqlmodel.sql.sqltypes.UTCDateTime(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###
