name: 🧪 Integration Tests

on: [push, pull_request, merge_group, workflow_dispatch]

jobs:
  tests:
    name: ⚗️ Test python${{ matrix.python-version }}
    uses: WGBH-MLA/.github/.github/workflows/pytest-with-postgres.yml@v1
    secrets: inherit
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']
    with:
      uv_args: --no-dev --extra test
      python_version: ${{ matrix.python-version }}
      pytest_args: -n auto --vcr-record=none --no_ci

  lint:
    name: 👕 Lint
    uses: WGBH-MLA/.github/.github/workflows/lint.yml@v1

  black:
    name: 🖤 Black
    uses: WGBH-MLA/.github/.github/workflows/black.yml@v1
